language: csharp

dotnet: 2.1.2
sudo: false

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
    - dotnet build dotNetSecondApp.sln -c Release
    - dotnet test -c Release --no-build UnitTest/UnitTest.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
